"""Add toggles for Prompt

Revision ID: 080490d7f2a0
Revises: ab136c533c49
Create Date: 2025-01-14 19:35:41.539813

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

from database.sql_model import *



# revision identifiers, used by Alembic.
revision: str = '080490d7f2a0'
down_revision: Union[str, None] = 'ab136c533c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt', sa.Column('toggles', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt', 'toggles')
    # ### end Alembic commands ###
