"""Add last_message_time for Room

Revision ID: 1ad1f6bf6462
Revises: 9a48c7975a2b
Create Date: 2025-01-17 23:57:29.571138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from database.sql_model import *



# revision identifiers, used by Alembic.
revision: str = '1ad1f6bf6462'
down_revision: Union[str, None] = '9a48c7975a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('last_message_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'last_message_time')
    # ### end Alembic commands ###
