"""Add suggest_prompt to room

Revision ID: 2a22c5ee299f
Revises: e7ca14ea03b7
Create Date: 2025-01-27 11:44:47.849495

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a22c5ee299f'
down_revision: Union[str, None] = 'e7ca14ea03b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('suggest_prompt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    with op.batch_alter_table('room') as batch_op:
        batch_op.create_foreign_key('room', 'prompt', ['suggest_prompt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room') as batch_op:
        batch_op.drop_constraint('room', type_='foreignkey')

    op.drop_column('room', 'suggest_prompt_id')
    # ### end Alembic commands ###
