"""Add use_stream for Prompt

Revision ID: 2a4f7bdcb022
Revises: 080490d7f2a0
Create Date: 2025-01-14 23:40:48.956125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from database.sql_model import *



# revision identifiers, used by Alembic.
revision: str = '2a4f7bdcb022'
down_revision: Union[str, None] = '080490d7f2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt', sa.Column('use_stream', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt', 'use_stream')
    # ### end Alembic commands ###
