"""Reset database and change id with uuid

Revision ID: 6586635b630e
Revises: 
Create Date: 2025-01-18 15:22:33.453215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from database.sql_model import *



# revision identifiers, used by Alembic.
revision: str = '6586635b630e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('displayName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profileImageId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_assets', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_id'), 'bot', ['id'], unique=False)
    op.create_table('image',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_file_id'), 'image', ['file_id'], unique=False)
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.create_table('persona',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('displayName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profileImageId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_id'), 'persona', ['id'], unique=False)
    op.create_table('prompt',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_config', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('use_stream', sa.Boolean(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('toggles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_id'), 'prompt', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_type'), 'prompt', ['type'], unique=False)
    op.create_table('room',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary_prompt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('re_summary_prompt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('translate_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('translate_prompt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('translate_only_assistant', sa.Boolean(), nullable=False),
    sa.Column('filters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_message_time', sa.DateTime(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['re_summary_prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['summary_prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['translate_prompt_id'], ['prompt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=False)
    op.create_table('conversation',
    sa.Column('room_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assistant_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_message_translated', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assistant_message_translated', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_created_at'), 'conversation', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_id'), 'conversation', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_room_id'), 'conversation', ['room_id'], unique=False)
    op.create_table('summary',
    sa.Column('room_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['summary.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_conversation_id'), 'summary', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_summary_created_at'), 'summary', ['created_at'], unique=False)
    op.create_index(op.f('ix_summary_id'), 'summary', ['id'], unique=False)
    op.create_index(op.f('ix_summary_is_top'), 'summary', ['is_top'], unique=False)
    op.create_index(op.f('ix_summary_parent'), 'summary', ['parent'], unique=False)
    op.create_index(op.f('ix_summary_room_id'), 'summary', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_room_id'), table_name='summary')
    op.drop_index(op.f('ix_summary_parent'), table_name='summary')
    op.drop_index(op.f('ix_summary_is_top'), table_name='summary')
    op.drop_index(op.f('ix_summary_id'), table_name='summary')
    op.drop_index(op.f('ix_summary_created_at'), table_name='summary')
    op.drop_index(op.f('ix_summary_conversation_id'), table_name='summary')
    op.drop_table('summary')
    op.drop_index(op.f('ix_conversation_room_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_created_at'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_prompt_type'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_id'), table_name='prompt')
    op.drop_table('prompt')
    op.drop_index(op.f('ix_persona_id'), table_name='persona')
    op.drop_table('persona')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_index(op.f('ix_image_file_id'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_bot_id'), table_name='bot')
    op.drop_table('bot')
    # ### end Alembic commands ###
