"""Add lore_book_id for bot

Revision ID: 6a1c7533b090
Revises: 8ac74f65787e
Create Date: 2025-01-29 13:18:38.608554

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a1c7533b090'
down_revision: Union[str, None] = '8ac74f65787e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.rename_table('lores', 'lore')
    except:
        pass
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lore_book_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key('bot', 'lorebook', ['lore_book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.drop_constraint('bot', type='foreignkey')
        batch_op.drop_column('lore_book_id')

    try:
        op.rename_table('lore', 'lores')
    except:
        pass
    # ### end Alembic commands ###
