"""Create OperationLog

Revision ID: 6a8aa0d0f6b0
Revises: a618cda3e3bc
Create Date: 2025-01-30 16:50:21.579578

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a8aa0d0f6b0'
down_revision: Union[str, None] = 'a618cda3e3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operationlog',
                    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('related_room_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('related_conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('operationlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operationlog_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operationlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operationlog_id'))

    op.drop_table('operationlog')
    # ### end Alembic commands ###
