"""Create GlobalSettings

Revision ID: 840f5a7d2e04
Revises: 6586635b630e
Create Date: 2025-01-19 11:16:29.410080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from database.sql_model import *



# revision identifiers, used by Alembic.
revision: str = '840f5a7d2e04'
down_revision: Union[str, None] = '6586635b630e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalsetting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_globalsetting_id'), 'globalsetting', ['id'], unique=False)
    op.create_index(op.f('ix_globalsetting_key'), 'globalsetting', ['key'], unique=True)
    op.create_index(op.f('ix_globalsetting_type'), 'globalsetting', ['type'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_globalsetting_type'), table_name='globalsetting')
    op.drop_index(op.f('ix_globalsetting_key'), table_name='globalsetting')
    op.drop_index(op.f('ix_globalsetting_id'), table_name='globalsetting')
    op.drop_table('globalsetting')
    # ### end Alembic commands ###
