"""Create StorageFile

Revision ID: a618cda3e3bc
Revises: 6a1c7533b090
Create Date: 2025-01-29 23:12:11.570205

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a618cda3e3bc'
down_revision: Union[str, None] = '6a1c7533b090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storagefile',
                    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('size', sa.Integer(), nullable=False),
                    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('storagefile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storagefile_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storagefile_path'), ['path'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storagefile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storagefile_path'))
        batch_op.drop_index(batch_op.f('ix_storagefile_id'))

    op.drop_table('storagefile')
    # ### end Alembic commands ###
