"""Create created_variants to image

Revision ID: c968d7df1a3a
Revises: f60974ef3e19
Create Date: 2025-01-22 17:46:06.005763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from database.sql_model import *



# revision identifiers, used by Alembic.
revision: str = 'c968d7df1a3a'
down_revision: Union[str, None] = 'f60974ef3e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('created_variants', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'created_variants')
    # ### end Alembic commands ###
