"""Create post_prompt for Bot

Revision ID: f60974ef3e19
Revises: 1c8165897d0f
Create Date: 2025-01-20 03:57:26.178813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from database.sql_model import *



# revision identifiers, used by Alembic.
revision: str = 'f60974ef3e19'
down_revision: Union[str, None] = '1c8165897d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('post_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'post_prompt')
    # ### end Alembic commands ###
